<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDxToW9q\Glpi_Kernel_KernelProductionContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDxToW9q/Glpi_Kernel_KernelProductionContainer.php') {
    touch(__DIR__.'/ContainerDxToW9q.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionContainer::class, false)) {
    \class_alias(\ContainerDxToW9q\Glpi_Kernel_KernelProductionContainer::class, Glpi_Kernel_KernelProductionContainer::class, false);
}

return new \ContainerDxToW9q\Glpi_Kernel_KernelProductionContainer([
    'container.build_hash' => 'DxToW9q',
    'container.build_id' => '1fcd91cb',
    'container.build_time' => 1769030141,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDxToW9q');
