<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF2zKuu6\Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF2zKuu6/Glpi_Kernel_KernelProductionDebugContainer.php') {
    touch(__DIR__.'/ContainerF2zKuu6.legacy');

    return;
}

if (!\class_exists(Glpi_Kernel_KernelProductionDebugContainer::class, false)) {
    \class_alias(\ContainerF2zKuu6\Glpi_Kernel_KernelProductionDebugContainer::class, Glpi_Kernel_KernelProductionDebugContainer::class, false);
}

return new \ContainerF2zKuu6\Glpi_Kernel_KernelProductionDebugContainer([
    'container.build_hash' => 'F2zKuu6',
    'container.build_id' => '25432d69',
    'container.build_time' => 1770639301,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF2zKuu6');
